---

- hosts: development
  remote_user: ubuntu
  sudo: yes
  vars_files:
    - vars.yml
  vars:
    domain: local.hatbarcelona.com
    certificates_folder: /home/{{ user }}/shared/certificates
  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"

  roles:
    - common
    - frontend
