---

- hosts: production
  remote_user: hatbarcelona
  become: yes
  vars_files:
    - vars.yml
  vars:
    domain: hatbarcelona.com
    certificates_folder: /etc/letsencrypt/live
  vars_prompt:
    - name: "create_certificates"
      prompt: "Create SSL Certificates (yes, no)"
      default: "no"

  roles:
    - common
    - frontend
    - role: letsencrypt
      letsencrypt_webroot_path: /home/{{ user }}/shared/public/{{ user }}.website.static
      letsencrypt_email: 'info@{{ domain }}'
      letsencrypt_cert_domains:
        - 'www.{{ domain }}'
        - 'next.{{ domain }}'
        - '{{ domain }}'
      letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
      when: create_certificates == 'yes'
